# Generated by Django 4.1.3 on 2022-11-04 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0007_alter_balance_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='trans_time',
            new_name='time_of_transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='trans_sum',
        ),
        migrations.AddField(
            model_name='transaction',
            name='sum_of_transaction',
            field=models.PositiveIntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to=settings.AUTH_USER_MODEL),
        ),
    ]
