# Generated by Django 4.1.3 on 2022-11-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_rename_trans_time_transaction_time_of_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='to_user',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
