# Generated by Django 4.1.3 on 2022-11-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_transaction_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='organization',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
